services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "8080:27017"
    # volumes:
    #   - mongo_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    # environment:
    #   MONGO_URL: mongodb://mongo:27017/mydatabase

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend